<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Shop\Controller\BasketController'        => __DIR__ . '/src/Shop/Controller/BasketController.php',
    'Shop\Controller\BasketControllerFactory' => __DIR__ . '/src/Shop/Controller/BasketControllerFactory.php',
    'Shop\Form\Basket'                        => __DIR__ . '/src/Shop/Form/Basket.php',
    'Shop\Form\BasketFactory'                 => __DIR__ . '/src/Shop/Form/BasketFactory.php',
    'Shop\Model\Hydrator\Basket'              => __DIR__ . '/src/Shop/Model/Hydrator/Basket.php',
    'Shop\Model\Hydrator\BasketFactory'       => __DIR__ . '/src/Shop/Model/Hydrator/BasketFactory.php',
    'Shop\Model\Validator\Basket'             => __DIR__ . '/src/Shop/Model/Validator/Basket.php',
    'Shop\Model\Validator\BasketFactory'      => __DIR__ . '/src/Shop/Model/Validator/BasketFactory.php',
    'Shop\Module'                             => __DIR__ . '/Module.php',
    'Shop\View\Helper\ShowBasket'             => __DIR__ . '/src/Shop/View/Helper/ShowBasket.php',
    'Shop\View\Helper\ShowBasketFactory'      => __DIR__ . '/src/Shop/View/Helper/ShowBasketFactory.php',
);
