<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'shop/basket/show'  => __DIR__ . '/view/shop/basket/show.phtml',
    'shop/basket/index' => __DIR__ . '/view/shop/basket/index.phtml',
);
