<?php
/**
 * ZF2rapid skeleton application
 *
 * @package    Application
 * @link       https://github.com/ZFrapid/zf2rapid-skeleton
 * @copyright  Copyright (c) 2014 - 2015 Ralf Eggert
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

/**
 * Index view script
 *
 * @package    Application
 */

$this->headTitle('application_title_error_404');
$this->h1('application_h1_error_404');
?>
<div class="jumbotron">
    <h2><?php echo $this->translate('application_h2_error_404'); ?></h2>
    <?php
    if (isset($this->reason) && $this->reason) {
        switch ($this->reason) {
            case 'error-controller-cannot-dispatch':
                $message = 'application_message_controller_cannot_dispatch';
                break;
            case 'error-controller-not-found':
                $message = 'application_message_controller_not_found';
                break;
            case 'error-controller-invalid':
                $message = 'application_message_controller_invalid';
                break;
            case 'error-router-no-match':
                $message = 'application_message_controller_no_match';
                break;
            default:
                $message = 'application_message_controller_other';
                break;
        }
    }
    ?>
    <p>
        <?php echo $this->translate('application_misc_reason') ?>:
        <?php echo $this->translate($message) ?>
    </p>
    <p class="pull-center">
        <a href="/" class="btn btn-success">
            <?php echo $this->translate('application_action_homepage'); ?>
        </a>
    </p>
</div>
