<?php
/**
 * ZF2 Application built by ZF2rapid
 *
 * @copyright (c) 2015 John Doe
 * @license http://opensource.org/licenses/MIT The MIT License (MIT)
 */


use BlogDomain\Model\Entity\CategoryEntity;

/** @var CategoryEntity $categoryEntity */
$categoryEntity = $this->categoryEntity;

$this->h1('category_admin_title_update');

$this->categoryDataForm->setAttribute('action', $this->url('category-admin/update', ['id' => $categoryEntity->getIdentifier()]));

echo $this->bootstrapForm($this->categoryDataForm);
?>
<p>
    <a class="btn btn-primary" href="<?php echo $this->url('category-admin'); ?>">
        <i class="fa fa-table"></i>
        <?php echo $this->translate('category_admin_action_index'); ?>
    </a>
</p>