<?php
/**
 * ZF2rapid skeleton application
 *
 * @package    Application
 * @link       https://github.com/ZFrapid/zf2rapid-skeleton
 * @copyright  Copyright (c) 2014 - 2015 Ralf Eggert
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

/**
 * Footer view script
 *
 * @package    Application
 */
?>
<footer id="footer">
    <div class="footer-top"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <h4>
                    <?php echo $this->translate(
                        'application_h4_footer_skeleton'
                    ); ?>
                </h4>
                <p>
                    <?php echo sprintf(
                        $this->translate('application_message_footer_skeleton'),
                        '<a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">',
                        '</a>'
                    ) ?>
                </p>
            </div>
            <div class="col-lg-4">
                <h4>
                    <?php echo $this->translate(
                        'application_h4_footer_links1'
                    ); ?>
                </h4>
                <ul>
                    <li>
                        <a href="http://framework.zend.com/" target="_blank">
                            <?php echo $this->translate(
                                'application_label_zfwebsite'
                            ); ?>
                        </a>
                    </li>
                    <li><a href="http://modules.zendframework.com/"
                           target="_blank">
                            <?php echo $this->translate(
                                'application_label_zfmodules'
                            ); ?>
                        </a>
                    </li>
                    <li><a href="https://github.com/zendframework/"
                           target="_blank">
                            <?php echo $this->translate(
                                'application_label_zfgithub'
                            ); ?>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="col-lg-4">
                <h4>
                    <?php echo $this->translate(
                        'application_h4_footer_links2'
                    ); ?>
                </h4>
                <ul>
                    <li>
                        <a href="https://github.com/ZFrapid/zf2rapid"
                           target="_blank">
                            <?php echo $this->translate(
                                'application_label_zf2rapid'
                            ); ?>
                        </a>
                    </li>
                    <li>
                        <a href="https://github.com/ZFrapid/zf2rapid-skeleton"
                           target="_blank">
                            <?php echo $this->translate(
                                'application_label_zf2rapid_skeleton'
                            ); ?>
                        </a>
                    </li>
                    <li>
                        <a href="http://www.ralfeggert.de"
                           target="_blank">
                            <?php echo $this->translate(
                                'application_label_ralfeggert'
                            ); ?>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>
