<?php
/**
 * ZF2rapid skeleton application
 *
 * @package    Application
 * @link       https://github.com/ZFrapid/zf2rapid-skeleton
 * @copyright  Copyright (c) 2014 - 2015 Ralf Eggert
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

/**
 * Header view script
 *
 * @package    Application
 */
?>
<div class="container">
    <header>
        <div class="row">
            <div class="col-md-4 col-sm-12">
                <a href="<?php echo $this->url('home'); ?>">
                    <img src="/assets/custom/img/logo.png" class="logo">
                </a>
            </div>
            <div class="col-md-8 col-sm-12 slogan">
                <?php echo $this->translate('application_misc_slogan'); ?>
            </div>
        </div>
    </header>
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"
                    data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">
                    <?php echo $this->translate(
                        'application_misc_toggle_navigation'
                    ); ?>
                </span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <?php
            $this->navigation('navigation')->menu()->setUlClass(
                'nav navbar-nav'
            );
            echo $this->navigation('navigation')->menu()->render();
            ?>
        </div>
    </nav>
</div>
