<?php
/**
 * ZF2rapid skeleton application
 *
 * @package    Application
 * @link       https://github.com/ZFrapid/zf2rapid-skeleton
 * @copyright  Copyright (c) 2014 - 2015 Ralf Eggert
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

/**
 * Layout view script
 *
 * @package    Application
 */

// set header
$this->headTitle()->setSeparator(' - ')->setAutoEscape(false);
$this->headTitle('application_title_default');
$this->headMeta()->setCharset('UTF-8');
$this->headMeta()->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
$this->headLink(array('rel'  => 'shortcut icon', 'href' => $this->basePath() . '/assets/custom/img/favicon.ico'));
$this->headLink()->appendStylesheet($this->basePath() . '/assets/vendor/bootstrap/css/bootstrap.min.css');
$this->headLink()->appendStylesheet($this->basePath() . '/assets/vendor/font-awesome/css/font-awesome.min.css');
$this->headLink()->appendStylesheet($this->basePath() . '/assets/custom/css/styles.css');
$this->headScript()->appendFile('https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js', 'text/javascript', array('conditional' => 'lt IE 9'));
$this->headScript()->appendFile('https://oss.maxcdn.com/respond/1.4.2/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9'));
$this->inlineScript()->prependFile('/assets/vendor/bootstrap/js/bootstrap.min.js', 'text/javascript');
$this->inlineScript()->prependFile('/assets/vendor/jquery/jquery.min.js', 'text/javascript');
?>
<?php echo $this->doctype() . "\n"; ?>
<html lang="en">
<head>
    <?php echo $this->headTitle() . "\n"; ?>
    <?php echo $this->headMeta() . "\n"; ?>
    <?php echo $this->headLink() . "\n"; ?>
    <?php echo $this->headScript() . "\n"; ?>
    <?php echo $this->headStyle() . "\n"; ?>
</head>
<body>
<?php echo $this->header; ?>
<div class="container">
    <?php echo $this->h1(); ?>
    <hr>
    <?php echo $this->bootstrapFlashMessenger()->render(); ?>
    <?php echo $this->content; ?>
</div>
<?php echo $this->footer; ?>
<?php echo $this->inlineScript() ?>
</body>
</html>
