<?php
/**
 * ZF2rapid skeleton application
 *
 * @package    Application
 * @link       https://github.com/ZFrapid/zf2rapid-skeleton
 * @copyright  Copyright (c) 2014 - 2015 Ralf Eggert
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */
use BlogDomain\Model\Entity\ArticleEntity;

/**
 * Index view script
 *
 * @package    Application
 */

$this->h1('application_h1_index_index');

?>
<?php /** @var ArticleEntity $articleEntity */ ?>
<?php foreach ($this->articleList as $articleEntity): ?>
    <h2><?php echo $articleEntity->getTitle() ?></h2>
    <p><em>From <?php echo $articleEntity->getAuthor() ?></em></p>
    <p><?php echo $articleEntity->getTeaser() ?></p>
    <p><em>Written on <?php echo $this->date($articleEntity->getCreated()) ?></em></p>
    <hr>
<?php endforeach; ?>

